version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: review-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_HOST: ${DATABASE_HOST}
    ports:
      - "3306:3306"

  redis:
    image: redis:6-alpine
    command: redis-server
    container_name: review-redis
    ports:
      - '6379:6379'
    networks:
      - service-net

networks:
  service-net:
