version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: review-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_HOST: ${DATABASE_HOST}
    ports:
      - "3306:3306"
